name: jitsi_meet_pro
description: Jitsi Meet Plugin - A plugin for integrating open source Jitsi Meet API in flutter. Jitsi Meet is secure, fully featured and allows completely free video conferencing made with https://jitsi.org, a collection of open source projects
version: 6.2.3
homepage: https://github.com/Gaurav-CareMonitor/jitsi_meet

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  jitsi_meet_plus_platform_interface: ^6.2.2 
  jitsi_meet_plus_web: ^6.2.2 

dev_dependencies:
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.gaurav.jitsi_meet_pro
        pluginClass: JitsiMeetPlugin
      ios:
        pluginClass: JitsiMeetPlugin
      web:
        default_package: jitsi_meet_plus_web