name: jitsi_meet_plus_platform_interface
description: A common platform interface for the jitsi meet plugin.
version: 6.2.2
homepage: https://github.com/Gaurav-CareMonitor/jitsi_meet

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_lints: ^2.0.1



